spring:
  datasource:
    url: jdbc:h2:file:~/library_dev
    driver-class-name: org.h2.Driver
    username: sa
    password: password

  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

logging:
  level:
    com.library: DEBUG
    org.springframework.web: DEBUG
