spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/library_prod}
    driver-class-name: org.postgresql.Driver
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:1234}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 20000

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    com.library: INFO
    org.springframework.web: WARN
  file:
    name: logs/library-management-system.log